In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
house = pd.read_csv('HousePrice.csv')

In [21]:
house.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [22]:
#dropping columns with null values
a = []
for col in house.columns:
    if int(house[col].isnull().sum())>0:
        a.append(col);
        house = house.drop([col], axis =1)
house = house.drop(columns = 'Id')

In [23]:
#getting dummies for all categorical attributes
for col in house.columns:
    if(house[col].dtype.name=='object'):
        temp = pd.get_dummies(house[col])
        house = pd.concat([house, temp], axis=1)
        house = house.drop(columns = col)

In [24]:
house.head()

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,...,ConLw,New,Oth,WD,Abnorml,AdjLand,Alloca,Family,Normal,Partial
0,60,8450,7,5,2003,2003,706,0,150,856,...,0,0,0,1,0,0,0,0,1,0
1,20,9600,6,8,1976,1976,978,0,284,1262,...,0,0,0,1,0,0,0,0,1,0
2,60,11250,7,5,2001,2002,486,0,434,920,...,0,0,0,1,0,0,0,0,1,0
3,70,9550,7,5,1915,1970,216,0,540,756,...,0,0,0,1,1,0,0,0,0,0
4,60,14260,8,5,2000,2000,655,0,490,1145,...,0,0,0,1,0,0,0,0,1,0

In [25]:
house.corr()

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,...,ConLw,New,Oth,WD,Abnorml,AdjLand,Alloca,Family,Normal,Partial
MSSubClass,1.000000,-0.139781,0.032628,-0.059316,0.027850,0.040581,-0.069836,-0.065649,-0.140759,-0.238518,...,0.014005,-0.045156,-0.014555,0.026359,0.005003,0.016241,0.030002,0.000983,0.024359,-0.051068
LotArea,-0.139781,1.000000,0.105806,-0.005636,0.014228,0.013788,0.214103,0.111170,-0.002618,0.260833,...,-0.015040,0.020039,-0.005722,-0.002292,-0.029126,-0.013208,0.008966,-0.010781,0.005711,0.022635
OverallQual,0.032628,0.105806,1.000000,-0.091932,0.572323,0.550684,0.239666,-0.059119,0.308159,0.537808,...,-0.021172,0.327412,-0.057962,-0.225013,-0.103535,-0.041677,-0.044950,-0.025515,-0.143282,0.323295
OverallCond,-0.059316,-0.005636,-0.091932,1.000000,-0.375983,0.073741,-0.046231,0.040229,-0.136841,-0.171098,...,-0.019779,-0.156175,-0.050663,0.163684,-0.046367,-0.038888,-0.033444,-0.023873,0.161642,-0.151659
YearBuilt,0.027850,0.014228,0.572323,-0.375983,1.000000,0.592855,0.249503,-0.049107,0.149040,0.391452,...,-0.023431,0.346954,0.012122,-0.238463,-0.110233,-0.045601,-0.010104,-0.035785,-0.158427,0.343895
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AdjLand,0.016241,-0.013208,-0.041677,-0.038888,-0.045601,-0.040294,-0.014874,-0.015130,-0.034618,-0.055895,...,-0.003073,-0.015827,-0.002378,0.020457,-0.014289,1.000000,-0.004772,-0.006177,-0.112080,-0.016038
Alloca,0.030002,0.008966,-0.044950,-0.033444,-0.010104,-0.020727,0.021369,-0.026277,-0.059130,-0.047002,...,-0.005337,-0.027489,-0.004131,0.035530,-0.024817,-0.004772,1.000000,-0.010729,-0.194663,-0.027856
Family,0.000983,-0.010781,-0.025515,-0.023873,-0.035785,-0.048056,0.000765,-0.007929,0.021534,0.019569,...,-0.006909,-0.035587,-0.005348,0.028599,-0.032128,-0.006177,-0.010729,1.000000,-0.252006,-0.036062
Normal,0.024359,0.005711,-0.143282,0.161642,-0.158427,-0.120577,-0.019560,0.041207,-0.153930,-0.160222,...,0.027414,-0.645698,-0.097031,0.634322,-0.582947,-0.112080,-0.194663,-0.252006,1.000000,-0.654323
Partial,-0.051068,0.022635,0.323295,-0.151659,0.343895,0.322837,0.044912,-0.085761,0.249315,0.266268,...,-0.017938,0.986819,-0.013885,-0.769559,-0.083419,-0.016038,-0.027856,-0.036062,-0.654323,1.000000

In [26]:
house.isnull().sum()

MSSubClass     0
LotArea        0
OverallQual    0
OverallCond    0
YearBuilt      0
              ..
AdjLand        0
Alloca         0
Family         0
Normal         0
Partial        0
Length: 216, dtype: int64

In [27]:
house['SalePrice'].head()

0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64

In [28]:
x = house.loc[:, house.columns!='SalePrice']
y = house['SalePrice']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)

scaled_x = scaler.transform(x_train)

In [29]:
from sklearn import linear_model
lasso = linear_model.Lasso(alpha=0.1)
lasso.fit(scaled_x, y_train)

c:\users\yaswa\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.017e+10, tolerance: 5.731e+08
  model = cd_fast.enet_coordinate_descent(

Lasso(alpha=0.1)

In [30]:
y_pred = lasso.predict(scaled_x)
from sklearn.metrics import r2_score
score = r2_score(y_pred, y_train)
score

0.9129777974901014

In [31]:
from sklearn import linear_model
ridge = linear_model.Ridge(alpha=0.1)
ridge.fit(scaled_x, y_train)

Ridge(alpha=0.1)

In [32]:
y_pred1 = ridge.predict(scaled_x)
from sklearn.metrics import r2_score
score1 = r2_score(y_pred1, y_train)
score1

0.9129730019850827

In [33]:
#scaling and checking accuracy on test data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_test)

scaled_x_test = scaler.transform(x_test)
y_pred_ltest = lasso.predict(scaled_x_test)
y_pred_rtest = ridge.predict(scaled_x_test)

scorel = r2_score(y_pred_ltest, y_test)
scorer = r2_score(y_pred_rtest, y_test)
print(scorel, scorer)

0.8591105571122558 0.8551921824397659

In [34]:
data = {'Metrics':["Accuracy"],'Lasso Regression': [scorel*100], 'Ridge Regression': [scorer*100]}  
result = pd.DataFrame(data)

In [35]:
result.set_index(["Metrics"])

          Lasso Regression  Ridge Regression
Metrics
Accuracy         85.911056         85.519218